export const LIVE_STREAM_EPISODE = {
  id: 999999,
  title:
    '[#프리한19] 우리가 잘못 알고 있던 상식들, 모두 알려드림! 🎯 알아두면 쓸모 있는 상식 zip | #티전드',
  subtitle: '차 안의 스튜디오, 지금 ON AIR',
  creator: 'tvN D ENT',
  img_url: '/tvN_channel_logo.png',
  audio_file: 'https://pickle-demo.netlify.app/Live_tgend.mp3',
  audioFile_dubbing: null,
  date: null,
  duration: '0',
  type: 'radio',
  created_at: null,
  program_id: 1,
  order_recent: 0,
  programs: {
    id: 1,
    title: 'tvN D ENT',
    img_url: '/tvN_channel_logo.png',
    is_live: true,
    created_at: null,
    broadcasting_id: 1,
    subtitle: 'Live Streaming',
    type: 'radio',
  },
};

export const LIVE_STREAM_EPISODE_EN = {
  id: 999999,
  title: `David Spade & Conan Remember Their Friend Norm Macdonald | Conan O'Brien Needs A Friend`,
  subtitle: 'Tune in LIVE, Stay with the stream',
  creator: 'Team Coco',
  img_url: '/teamcoco_channel_logo.png',
  audio_file: 'https://pickle-demo.netlify.app/Live_teamcoco.mp3',
  audioFile_dubbing: null,
  date: null,
  duration: '0',
  type: 'radio',
  created_at: null,
  program_id: 1,
  order_recent: 0,
  programs: {
    id: 1,
    title: 'Team Coco',
    img_url: '/teamcoco_channel_logo.png',
    is_live: true,
    created_at: null,
    broadcasting_id: 1,
    subtitle: 'Live Streaming',
    type: 'radio',
  },
};
