import type { PreferenceQuestion } from '../types/preference';

export const PREFERENCE_QUESTIONS: PreferenceQuestion[] = [
  {
    id: 'age',
    question: '연령대를 선택해주세요.',
    type: 'single',
    options: [
      { label: '20대', value: '20s' },
      { label: '30대', value: '30s' },
      { label: '40대', value: '40s' },
      { label: '50대', value: '50s' },
      { label: '60대+', value: '60s+' },
    ],
  },
  {
    id: 'genres',
    question: '관심 있는 주제를 선택해주세요.',
    type: 'multiple',
    options: [
      { label: '일일 드라마', value: 'daily_drama' },
      { label: '경제·투자', value: 'economy' },
      { label: '인문·교양', value: 'humanities' },
      { label: '책', value: 'book' },
      { label: '연애·공부', value: 'love_study' },
      { label: '키즈', value: 'kids' },
      { label: '종교', value: 'religion' },
      { label: '일어·공부', value: 'japanese' },
      { label: '트렌드', value: 'trend' },
      { label: 'ASMR', value: 'asmr' },
      { label: '유식', value: 'knowledge' },
      { label: '일상·토크', value: 'daily_talk' },
      { label: '시사·정치', value: 'politics' },
      { label: '힐링', value: 'healing' },
      { label: '스포츠', value: 'sports' },
      { label: '마스터리', value: 'mastery' },
      { label: '뉴스', value: 'news' },
      { label: '건강', value: 'health' },
    ],
  },
  {
    id: 'purpose',
    question: '현재 어떤 기분에 어울리는 콘텐츠가 좋나요?',
    type: 'single',
    options: [
      { label: '피곤함', value: 'tired' },
      { label: '스트레스', value: 'stress' },
      { label: '기분전환', value: 'mood_change' },
      { label: '여유로움', value: 'relaxed' },
      { label: '긴장함', value: 'tense' },
      { label: '호기심', value: 'curious' },
      { label: '집중', value: 'focused' },
    ],
  },
  {
    id: 'contentLength',
    question: '어느 정도 길이의 콘텐츠가 편하신가요?',
    type: 'single',
    options: [
      { label: '10분 이하', value: 'under_10' },
      { label: '10~30분', value: '10_30' },
      { label: '30~60분', value: '30_60' },
      { label: '60분 이상', value: 'over_60' },
    ],
  },
  {
    id: 'contentType',
    question: '어떤 콘텐츠 스타일을 더 듣고 싶나요?',
    type: 'single',
    options: [
      { label: '대화형', value: 'conversation' },
      { label: '정보형', value: 'information' },
      { label: '스토리형', value: 'story' },
      { label: '인터뷰형', value: 'interview' },
    ],
  },
  {
    id: 'mood',
    question: '어떤 상황에서 주로 운전하시나요?',
    type: 'single',
    options: [
      { label: '출퇴근길', value: 'commute' },
      { label: '여행·중', value: 'travel' },
      { label: '출장·중', value: 'business' },
      { label: '드라이브', value: 'drive' },
      { label: '아이와 함께', value: 'with_kids' },
      { label: '아간 운전', value: 'night' },
      { label: '초행길', value: 'new_route' },
    ],
  },
  {
    id: 'time',
    question: '주로 어떤 시간대에 운전하시나요?',
    type: 'single',
    options: [
      { label: '아침', value: 'morning' },
      { label: '낮', value: 'day' },
      { label: '저녁', value: 'evening' },
      { label: '야간', value: 'night' },
      { label: '새벽', value: 'dawn' },
    ],
  },
  {
    id: 'companion',
    question: '운전 할 때 어떤 말이 편한가요?',
    type: 'single',
    options: [
      { label: '경쾌한 말투', value: 'cheerful' },
      { label: '도덕 위주', value: 'moral' },
      { label: '고속도로 위주', value: 'highway' },
      { label: '단거리 반복', value: 'short_repeat' },
    ],
  },
  {
    id: 'tone',
    question: '주로 누구와 함께 운전하시나요?',
    type: 'single',
    options: [
      { label: '혼자', value: 'alone' },
      { label: '가족', value: 'family' },
      { label: '아이', value: 'child' },
      { label: '친구/지인', value: 'friend' },
      { label: '편견률', value: 'various' },
    ],
  },
  {
    id: 'diversity',
    question: '해외 콘텐츠 비중을 어떻게 할까요?',
    type: 'slider',
    min: 0,
    max: 100,
    step: 25,
  },
];

export const DEFAULT_PREFERENCE_STATE = {
  age: '30s',
  genres: ['daily_drama', 'humanities', '10_30'],
  purpose: 'tired',
  contentLength: '10_30',
  contentType: 'conversation',
  mood: 'commute',
  time: 'morning',
  companion: 'cheerful',
  tone: 'alone',
  diversity: 50,
};
