import type { PreferenceQuestion } from '../types/preference';

export const PREFERENCE_QUESTIONS: PreferenceQuestion[] = [
  {
    id: 'age',
    question: '연령대를 선택해주세요.',
    type: 'single',
    options: [
      { label: '20대', value: '20s' },
      { label: '30대', value: '30s' },
      { label: '40대', value: '40s' },
      { label: '50대', value: '50s' },
      { label: '60대+', value: '60s+' },
    ],
  },
  {
    id: 'genres',
    question: '관심 있는 주제를 선택해주세요.',
    type: 'multiple',
    options: [
      { label: '영화·드라마', value: 'movie_drama' },
      { label: '경제·투자', value: 'economy' },
      { label: '인문·교양', value: 'humanities' },
      { label: '언어공부', value: 'language' },
      { label: '키즈', value: 'kids' },
      { label: '트렌드', value: 'trend' },
      { label: 'ASMR', value: 'asmr' },
      { label: '뮤직', value: 'music' },
      { label: '시사·정치', value: 'politics' },
      { label: '힐링', value: 'healing' },
      { label: '뉴스', value: 'news' },
      { label: '일상·토크', value: 'daily_talk' },
      { label: '스포츠', value: 'sports' },
      { label: '책', value: 'books' },
      { label: '마스터리', value: 'mistery' },
      { label: '건강', value: 'health' },
    ],
  },
  {
    id: 'purpose',
    question: '현재 어떤 기분에 어울리는 콘텐츠가 좋나요?',
    type: 'multiple',
    options: [
      { label: '기분전환', value: 'mood_change' },
      { label: '피곤함', value: 'tired' },
      { label: '스트레스', value: 'stress' },
      { label: '여유로움', value: 'relaxed' },
      { label: '긴장함', value: 'tense' },
      { label: '집중', value: 'focused' },
      { label: '호기심', value: 'curious' },
    ],
  },
  {
    id: 'contentLength',
    question: '어느 정도 길이의 콘텐츠가 편하신가요?',
    type: 'multiple',
    options: [
      { label: '10분 이하', value: 'under_10' },
      { label: '10~30분', value: '10_30' },
      { label: '30~60분', value: '30_60' },
      { label: '60분 이상', value: 'over_60' },
    ],
  },
  {
    id: 'contentType',
    question: '어떤 콘텐츠 스타일을 더 듣고 싶나요?',
    type: 'multiple',
    options: [
      { label: '대화형', value: 'conversation' },
      { label: '정보형', value: 'information' },
      { label: '스토리형', value: 'story' },
      { label: '인터뷰형', value: 'interview' },
    ],
  },
  {
    id: 'mood',
    question: '어떤 상황에서 주로 운전하시나요?',
    type: 'multiple',
    options: [
      { label: '출퇴근길', value: 'commute' },
      { label: '여행 중', value: 'travel' },
      { label: '출장 중', value: 'business' },
      { label: '드라이브', value: 'drive' },
      { label: '아간 운전', value: 'night' },
      { label: '초행길', value: 'new_route' },
    ],
  },
  {
    id: 'time',
    question: '주로 어떤 시간대에 운전하시나요?',
    type: 'multiple',
    options: [
      { label: '아침', value: 'morning' },
      { label: '낮', value: 'day' },
      { label: '저녁', value: 'evening' },
      { label: '야간', value: 'night' },
      { label: '새벽', value: 'dawn' },
    ],
  },
  {
    id: 'environment',
    question: '운전 환경은 어떤 편인가요?',
    type: 'multiple',
    options: [
      { label: '정체가 많아요', value: 'traffic' },
      { label: '도심 위주', value: 'city' },
      { label: '고속도로 위주', value: 'highway' },
      { label: '단거리 반복', value: 'short' },
    ],
  },
  {
    id: 'companion',
    question: '주로 누구와 함께 운전하시나요?',
    type: 'multiple',
    options: [
      { label: '혼자', value: 'alone' },
      { label: '친구/지인', value: 'friend' },
      { label: '가족', value: 'family' },
      { label: '아이', value: 'child' },
      { label: '반려동물', value: 'pet' },
    ],
  },
  {
    id: 'diversity',
    question: '해외 콘텐츠 비중을 어떻게 할까요?',
    type: 'slider',
    min: 0,
    max: 100,
    step: 25,
  },
];

export const DEFAULT_PREFERENCE_STATE = {
  age: '30s',
  genres: ['movie_drama', 'humanities', 'language', 'trend', 'music', 'daily_talk', 'mistery'],
  purpose: ['tired', 'stress'],
  contentLength: ['10_30', '30_60'],
  contentType: ['conversation', 'story'],
  mood: ['commute'],
  time: ['morning', 'dawn'],
  environment: ['traffic', 'city'],
  companion: ['alone', 'friend', 'pet'],
  diversity: 50,
};
